name: messenger_clone_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  async: ^2.11.0
  auto_route: ^9.2.1+1
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  pretty_dio_logger: ^1.4.0
  reactive_forms: ^17.0.1
  retrofit: ^4.2.0
  rxdart: ^0.28.0
  socket_io_client: ^3.0.0-beta.2
  talker_flutter: ^4.4.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.0

flutter:
  uses-material-design: true
